[package]
name = "lucky_ball"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["android", "ios"]

[features]
default = ["inspector"]
inspector = ["bevy-inspector-egui", "iyes_perf_ui"]

[dependencies]
avian3d = "0.1.2"
bevy = "0.14.2"
bevy-inspector-egui = { version = "0.26.0", optional = true }
bevy_asset_loader = "0.21.0"
bevy_color = "0.14.3"
bevy_crossbeam_event = "0.6.0"
bevy_kira_audio = "0.20.0"
bevy_mod_picking = "0.20.1"
bevy_panorbit_camera = "0.19.3"
bevy_tweening = "0.11.0"
iyes_perf_ui = { version = "0.3.0", optional = true }
rand = "0.8.5"
serde = "1.0.210"
serde_json = "1.0.128"


[profile.release]
codegen-units = 1
