[package]
name = "lucky_ball"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["android", "ios"]

[features]
default = ["inspector"]
inspector = ["bevy-inspector-egui", "iyes_perf_ui"]

[dependencies]
avian3d = { version = "0.1.2" }
bevy = "0.14.2"
bevy-inspector-egui = { version = "0.26.0", optional = true }
bevy_asset_loader = "0.21.0"
bevy_color = "0.14.3"
bevy_crossbeam_event = "0.6.0"
bevy_kira_audio = { version = "0.20.0", features = ["mp3"] }
bevy_mod_picking = "0.20.1"
bevy_panorbit_camera = "0.19.3"
bevy_tweening = "0.11.0"
iyes_perf_ui = { version = "0.3.0", optional = true }
rand = "0.8.5"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
directories = "5.0.1"
uuid = "1.10.0"
chrono = "0.4.38"

[target.'cfg(target_os = "android")'.dependencies]
jni_fn = "0.1.2"
jni = "0.21.1"
ndk-context = "0.1"

[target.'cfg(target_os = "ios")'.dependencies]
raw-window-handle = "0.6.0"

[patch.crates-io]
winit = { git = "https://github.com/lsy969999/winit.git", branch = "patch-ios-0.30.0" }

[profile.release]
# lto = true
# opt-level = 3
codegen-units = 1
# incremental = false
# debug = false
